### ISSUE TITLE
Paste title length

### ISSUE THREAD

**Issue by pcolmer** [linaro-marketing/stikked_theme#2]
The official Stikked sample pastebin (https://paste.scratchbook.ch/) allows a title this long:

`This is a very long stikked title because I want t`

but pasting that into https://pastebin1804.linaro.org results in the title getting truncated to:

`This is a very long stikked titl`

**Comment by kylekirkby** [comment]
I've resolved these issues in [this PR](https://github.com/linaro-marketing/stikked_theme/pull/5) I believe. Could you test and let me know?

Cheers!
