### ISSUE TITLE
Linewrapped text in a paste gets displayed incorrectly

### ISSUE THREAD

**Issue by pcolmer** [linaro-marketing/stikked_theme#4]
https://pastebin1804.linaro.org/view/c7a9a67e shows a "virtual" additional horizontal scrollbar where line #4 has wrapped.

**Comment by kylekirkby** [comment]
I've resolved these issues in [this PR](https://github.com/linaro-marketing/stikked_theme/pull/5) I believe. Could you test and let me know?

Cheers!
